### ISSUE TITLE
Highlight color for command palette could use some increased contrast

### ISSUE THREAD

**Issue by jsunsawyer** [emily-curry/base16-tomorrow-dark-vscode#2]
There seems to be a separate highlight color when using arrows to traverse the list of items vs hovering with a cursor. The cursor hover is much more clear, while arrow navigation is super faint.

**Comment by emily-curry** [comment]
Hey, thanks for opening this issue! It had been bothering me for a bit too, I just hadn't got around to it. 

I've fixed this in a58f67ce84a39a33d22ac3021fecccefe1dc3ac5, v0.0.18.
